prefix = "root"
dirs = ["source_files"]

[server]
host = "127.0.0.1"
port = 9080

[s3]
host = "127.0.0.1"
port = 9090
region = "eu-central-1"
bucket_name = "images"
access_key = "minioadmin"
secret_key = "minioadmin"
